# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("user.proto", :syntax => :proto3) do
    add_message "user.UserResponse" do
      optional :first_name, :string, 1
      optional :last_name, :string, 2
      optional :email, :string, 3
      optional :phone_number, :string, 4
      optional :id, :int64, 5
    end
    add_message "user.UserRequest" do
      optional :id, :int64, 1
    end
  end
end

module User
  UserResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("user.UserResponse").msgclass
  UserRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("user.UserRequest").msgclass
end
