# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: user.proto for package 'user'

require 'grpc'
require 'user_pb'

module User
  module User
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'user.User'

      rpc :UserInformation, ::User::UserRequest, ::User::UserResponse
    end

    Stub = Service.rpc_stub_class
  end
end
